// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tfzvhsrdvkycsusnknso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmenZoc3Jkdmt5Y3N1c25rbnNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NjcwNDQsImV4cCI6MjA3MDU0MzA0NH0.NgPmDyb2mOjY1sI8i0Ff3LZgHhx9oRXFHBbLyE0cZ8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);